# Generated by Django 4.0 on 2022-01-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('name_pl', models.TextField(max_length=100, null=True)),
                ('name_ru', models.TextField(max_length=100, null=True)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='title')),
                ('title_pl', models.TextField(max_length=150, null=True, verbose_name='title')),
                ('title_ru', models.TextField(max_length=150, null=True, verbose_name='title')),
                ('main_photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='main photo')),
                ('publication_date', models.DateField(max_length=20, verbose_name='date of publication')),
                ('intro_text', models.TextField(max_length=2000, verbose_name='intro')),
                ('intro_text_pl', models.TextField(max_length=2000, null=True, verbose_name='intro')),
                ('intro_text_ru', models.TextField(max_length=2000, null=True, verbose_name='intro')),
                ('main_text', models.TextField(blank=True, max_length=10000, verbose_name='main text')),
                ('main_text_pl', models.TextField(blank=True, max_length=10000, null=True, verbose_name='main text')),
                ('main_text_ru', models.TextField(blank=True, max_length=10000, null=True, verbose_name='main text')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('category', models.ManyToManyField(blank=True, related_name='posts', to='bianka_site.Category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField(max_length=100, verbose_name='user name')),
                ('text', models.TextField(max_length=2000, verbose_name='comment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bianka_site.comment', verbose_name='komentarz nadrzędny')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bianka_site.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
